# Generated by Django 4.2.4 on 2023-08-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namemodel',
            name='updated_at',
            field=models.TimeField(auto_now=True),
        ),
    ]
